import 'package:flutter/material.dart';

// ============================================================
// App Theme — Auto-generated by AgentXLabs
// Design tokens injected from job context
// Primary: #E63946 | Font: Poppins
// ============================================================

class AppTheme {
  // ── Colour tokens ──────────────────────────────────────────
  static const Color primary        = Color(0xFFE63946);
  static const Color secondary      = Color(0xFF1A1A2E);
  static const Color background     = Color(0xFF121212);
  static const Color surface        = Color(0xFF1E1E2E);
  static const Color error          = Color(0xFFCF6679);
  static const Color success        = Color(0xFF2DC653);
  static const Color textPrimary    = Color(0xFFFFFFFF);
  static const Color textSecondary  = Color(0xFFB0B0B0);

  // ── Primary variants ───────────────────────────────────────
  static Color primaryLight  = primary.withOpacity(0.15);
  static Color primaryMid    = primary.withOpacity(0.6);

  // ── Spacing tokens ─────────────────────────────────────────
  static const double spaceXS  = 4.0;
  static const double spaceSM  = 8.0;
  static const double spaceMD  = 16.0;
  static const double spaceLG  = 24.0;
  static const double spaceXL  = 32.0;
  static const double spaceXXL = 48.0;

  // ── Border radius ──────────────────────────────────────────
  static const double radiusSM  = 4.0;
  static const double radiusMD  = 12.0;
  static const double radiusLG  = 20.0;
  static const double radiusPill = 999.0;

  // ── Theme data ─────────────────────────────────────────────
  static ThemeData get darkTheme => ThemeData(
    useMaterial3: true,
    brightness: Brightness.dark,
    colorScheme: ColorScheme.dark(
      primary:    primary,
      secondary:  secondary,
      background: background,
      surface:    surface,
      error:      error,
      onPrimary:  Colors.white,
      onSecondary: Colors.white,
      onBackground: textPrimary,
      onSurface:  textPrimary,
    ),
    scaffoldBackgroundColor: background,
    fontFamily: 'Poppins',

    appBarTheme: const AppBarTheme(
      backgroundColor: background,
      foregroundColor: textPrimary,
      elevation: 0,
      centerTitle: false,
      titleTextStyle: TextStyle(
        color: textPrimary,
        fontSize: 20,
        fontWeight: FontWeight.w600,
        fontFamily: 'Poppins',
      ),
    ),

    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        backgroundColor: primary,
        foregroundColor: Colors.white,
        minimumSize: const Size(double.infinity, 52),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(radiusMD),
        ),
        textStyle: const TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w600,
          fontFamily: 'Poppins',
        ),
      ),
    ),

    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        foregroundColor: primary,
        side: const BorderSide(color: primary, width: 1.5),
        minimumSize: const Size(double.infinity, 52),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(radiusMD),
        ),
      ),
    ),

    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: surface,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(radiusMD),
        borderSide: BorderSide.none,
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(radiusMD),
        borderSide: const BorderSide(color: primary, width: 1.5),
      ),
      hintStyle: const TextStyle(color: textSecondary, fontSize: 14),
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
    ),

    cardTheme: CardThemeData(
      color: surface,
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(radiusLG),
      ),
    ),

    bottomNavigationBarTheme: const BottomNavigationBarThemeData(
      backgroundColor: surface,
      selectedItemColor: primary,
      unselectedItemColor: textSecondary,
      type: BottomNavigationBarType.fixed,
      elevation: 0,
    ),

    textTheme: const TextTheme(
      displayLarge:  TextStyle(fontSize: 32, fontWeight: FontWeight.w700, color: textPrimary),
      displayMedium: TextStyle(fontSize: 24, fontWeight: FontWeight.w700, color: textPrimary),
      displaySmall:  TextStyle(fontSize: 20, fontWeight: FontWeight.w600, color: textPrimary),
      bodyLarge:     TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: textPrimary),
      bodyMedium:    TextStyle(fontSize: 14, fontWeight: FontWeight.w400, color: textSecondary),
      labelSmall:    TextStyle(fontSize: 12, fontWeight: FontWeight.w400, color: textSecondary),
    ),
  );

  static ThemeData get lightTheme => ThemeData(
    useMaterial3: true,
    brightness: Brightness.light,
    colorScheme: ColorScheme.light(
      primary:    primary,
      secondary:  secondary,
      background: Colors.white,
      surface:    const Color(0xFFF8F9FA),
      error:      error,
      onPrimary:  Colors.white,
      onBackground: const Color(0xFF1A1A2E),
      onSurface:  const Color(0xFF1A1A2E),
    ),
    scaffoldBackgroundColor: Colors.white,
    fontFamily: 'Poppins',
  );
}
